"""empty message

Revision ID: 9e045e47e176
Revises: b13251a0bab9
Create Date: 2021-11-17 15:29:20.439221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e045e47e176'
down_revision = 'b13251a0bab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professor', sa.Column('img_profile', sa.String(length=200), nullable=True))
    op.add_column('student', sa.Column('img_profile', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'img_profile')
    op.drop_column('professor', 'img_profile')
    # ### end Alembic commands ###
