"""empty message

Revision ID: e2271974e861
Revises: 76567fe40af8
Create Date: 2021-11-12 18:39:09.623455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2271974e861'
down_revision = '76567fe40af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('professor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'services', 'professor', ['professor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'professor_id')
    # ### end Alembic commands ###
